name: gcc-13

on:
  workflow_dispatch:

jobs:
  gcc-13:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: false
        install: >-
          base-devel
          git
          mingw-w64-ucrt-x86_64-binutils
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-gmp
          mingw-w64-ucrt-x86_64-isl
          mingw-w64-ucrt-x86_64-libiconv
          mingw-w64-ucrt-x86_64-mpc
          mingw-w64-ucrt-x86_64-mpfr 
          mingw-w64-ucrt-x86_64-windows-default-manifest 
          mingw-w64-ucrt-x86_64-winpthreads 
          mingw-w64-ucrt-x86_64-zlib 
          mingw-w64-ucrt-x86_64-zstd 
          mingw-w64-ucrt-x86_64-gperf
          mingw-w64-ucrt-x86_64-autotools
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash    
    - uses: actions/checkout@main
    
    - name: Setup git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: build 
      shell: msys2 {0}
      run: |              
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest/mingw-w64-ucrt-x86_64-headers-git-10.0.0.r201.g931ca20b2-1-any.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest/mingw-w64-ucrt-x86_64-crt-git-10.0.0.r201.g931ca20b2-1-any.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest/mingw-w64-ucrt-x86_64-mcfgthread-1.5.alpha.1.5.g5b5ddc9-1-any.pkg.tar.zst
        curl -OL https://github.com/${{ github.repository }}/releases/download/latest/mingw-w64-ucrt-x86_64-mcfgthread-libs-1.5.alpha.1.5.g5b5ddc9-1-any.pkg.tar.zst
        pacman -U *.tar.zst --noconfirm      
        cd mingw-w64-gcc; MINGW_ARCH=ucrt64 makepkg-mingw -sLf
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: gcc*
        fail-if-no-assets: false
        fail-if-no-release: false 
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mingw-w64-gcc/*.tar.*
        tag: latest
        overwrite: true
        file_glob: true
