name: mcfgthread-git

on:
  workflow_dispatch:

jobs:
  mcfgthread-git:
    runs-on: windows-2022
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        release: false
        install: base-devel git mingw-w64-x86_64-toolchain
    - name: Prepare
      run: git config --global core.autocrlf input
      shell: bash    
    - uses: eko5624/checkout@v2
    - name: build 
      shell: msys2 {0}
      run: |      
        cd /d/a/mcfgthread/mcfgthread//mingw-w64-mcfgthread-git; MINGW_ARCH=ucrt64 makepkg-mingw        
    - name: Delete
      uses: eko5624/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        assets: mingw-w64-ucrt-x86_64-mcfgthread-git*
        fail-if-no-assets: false
        fail-if-no-release: false 
    - name: Upload
      uses: eko5624/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: mingw-w64-mcfgthread-git/*.tar.*
        tag: latest
        overwrite: true
        file_glob: true
